import Head from 'next/head'
import Header from '../components/Header';
import SearchArtist from '../components/SearchArtist';
import SearchSongs from '../components/SearchSongs';
export default function Home() {
  return (
    <>
      <Head>
        <title>sinhalasongs | home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header title="SINHALA SONGS" desc="Download your favorite songs here" />

      <div className="w3-row-padding w3-pale-blue">
        <div className="w3-half w3-panel w3-margin-bottom">
          <img src="/music.gif" alt='1489x838' className="w3-image w3-greyscale" style={{width:'100%'}} />
        </div>
        <div className="w3-half w3-panel w3-margin-bottom">
          <h3><b>ABOUT</b></h3>
          <h6 className='w3-justify w3-opacity'>
            Welcome to the music download center for Sri Lanka, sinhalasongs.vercel.app. We're committed to giving you excellent service at no cost while maintaining your privacy and enjoyment, with a focus on high quality, speed, and availability around-the-clock. Any form of user feedback on our quality and services is always welcome. Do not hesitate to contact us if you have any inquiries or suggestions.
          </h6>
        </div>
      </div>

      <div className="w3-row-padding w3-pale-red">
          <div className="w3-panel ">
            <p className='w3-large w3-wide'><i>"Music is the universal language of mankind."</i></p>
            <p>- Henry Wadsworth Longfellow</p>
          </div>
      </div>
      <div className="w3-row-padding w3-pale-green">
        <div className="w3-half w3-padding">
            <SearchArtist />
        </div>
        <div className="w3-half">
            <SearchSongs /> 
        </div>
      </div>

      <div className='w3-padding-32 w3-pale-green'></div>

    </>
  )
}
