import Head from 'next/head'
import Header from '../components/Header';
import SearchArtist from '../components/SearchArtist';
export default function Home() {
  return (
    <>
      <Head>
        <title>sinhalasongs | home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header title="SINHALA SONGS" desc="Download your favorite songs here" />

      <div className="w3-row-padding w3-pale-blue">
        <div className="w3-half w3-panel w3-margin-bottom">
          <img src="/music.gif" alt='1489x838' className="w3-image w3-greyscale" style={{width:'100%'}} />
        </div>
        <div className="w3-half w3-panel w3-margin-bottom">
          <h3><b>ABOUT</b></h3>
          <h6 className='w3-justify w3-opacity'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. 
          </h6>
        </div>
      </div>

      <div className="w3-row-padding w3-pale-red">
        <div className="w3-panel ">
          <p className='w3-large w3-wide'><i>"Music is the universal language of mankind."</i></p>
          <p>- Henry Wadsworth Longfellow</p>
        </div>
      </div>

      <div className="w3-row-padding w3-pale-green">
        <div className="w3-half w3-panel">
            <SearchArtist />
        </div>
        <div className="w3-half w3-panel">
            <p>
              <input className='w3-input' id="song" type="search" dir="ltr" spellCheck={false} autoCorrect="off" autoComplete="off" autoCapitalize="off" maxLength="2048" tabIndex="1" />
            </p>
            <p className='w3-center'>
              <button type="button" className="w3-button w3-light-grey" >SEARCH</button>
            </p>  
        </div>
      </div>

      <div className='w3-padding'></div>

    </>
  )
}
